### ISSUE TITLE
OSD information position and measurement unit

### ISSUE THREAD

**Issue by Gaastragtx** [FPVTools/BitsyOSD#3]
Hi, after a series of problems with the character file and the fontupload.js file, I installed the firmware and I have also connected the GPS successfully.
Now I have two questions: if I want to change the position of OSD information, what should I change? 
Also, if you want to change from miles to km/h and from feet to meters, how can I do? Thank you

**Comment by flyandi** [comment]
Howdy- all the layout settings are located in ```const.h```. Look at the ```LAYOUT``` definitions. The positions represent X/Y coordinates on the screen - depending on the screen it is 80x25 positions.

For the miles to km/h, look at ```config.h``` which defines the units. U can configure each unit representation individually.

**Comment by Gaastragtx** [comment]
Many thanks for the quick response. I have successfully modified the layout and I began to understand how to change other parameters.
This project is fantastic and that's what I was looking for.
Can I have the complete picture of available characters? The image published in the blog has its sides cut off and not seen all the symbols.
Thank you.

**Comment by flyandi** [comment]
See here:

![bitsyosd-font](https://user-images.githubusercontent.com/329973/28399740-b9e5fd80-6cc3-11e7-981a-0cf41414c064.png)

**Comment by flyandi** [comment]
I also added this preview to the project.
