### ISSUE TITLE
Question about soldering the GPS directly

### ISSUE THREAD

**Issue by dieideeistgut** [FPVTools/BitsyOSD#4]
Hello, stated in your Readme is the option to solder the GPS directly, 
sadly images disappeared from the googlecode-page you linked up (or is it just me?). 

Any chance you  can tell me how to create the adapting-cable, or just bang it right on there?
Would be very helpful. Thanks in advance and thanks so much for BitsyOSD.

Edit: I'd just connect it like this to a micro MinimOSD - correct me if i'm wrong please:

![](http://pimousse.be/wp-content/uploads/2017/01/OSD_5-300x218.jpg)

**Comment by flyandi** [comment]
Oh I just noticed this - yeah the images are gone. It seems Google shutdown external linking across the board. 

So I actually just soldered headers to those pads and than use standard RC cables to connect to the GPS.

**Comment by flyandi** [comment]
So I added the original breadout board that I designed to the project. I have to make a better design and put it on Oshpark so it's easier to get the thing hooked up and soldered.

![image](https://user-images.githubusercontent.com/329973/28400256-bccade64-6cc6-11e7-9681-d21aef5ef253.png)

![image](https://user-images.githubusercontent.com/329973/28400284-d32afdce-6cc6-11e7-8e24-28f415ae46e3.png)
